server:
  port: 8090

  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

spring:
  application:
    name: api-gateway
  ## GATEWAY CONFIGURATIONS
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
            allowedHeaders: "*"


# JWT
#jwtKeyPath: conf/jwt_rsa_pub.pem
jwtKeyPath: KDmCIthmqx5LQmqrP4F4ynMUDkV6PxKKvUvTA2fyjAs=

